[profile.default]
contracts = 'contracts'
test = 'tests'
libs = ['modules']
optimizer = false
block_timestamp = 1_685_721_539
gas_limit = "18446744073709551615"
verbosity = 3
gas_reports = ["EmergencyModule", "RecapitalizationModule", "MapleTokenProxy"]

[profile.default.fuzz]
runs = 1_000

[profile.default.invariant]
runs = 100
depth = 100
fail_on_revert = true

[profile.ci]
optimizer = true
optimizer_runs = 200

[profile.ci.fuzz]
runs = 100_000

[profile.ci.invariant]
runs = 100
depth = 1_000
