name: mplv2
version: 1.0.0
source: contracts
packages:
  - path: contracts/EmergencyModule.sol
    contractName: EmergencyModule
  - path: contracts/RecapitalizationModule.sol
    contractName: RecapitalizationModule
  - path: contracts/MapleToken.sol
    contractName: MapleToken
  - path: contracts/MapleTokenInitializer.sol
    contractName: MapleTokenInitializer
  - path: contracts/MapleTokenProxy.sol
    contractName: MapleTokenInitializer
customDescription: Maple V2 Token Artifacts and ABIs
