name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  # Check code is formatted correctly.
  format:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Check all linter rules are satisfied.
  lint:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Build contracts.
  build:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Run unit tests.
  test:
    runs-on: ubuntu-latest
    needs:
    steps:
      - uses: actions/checkout@v2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          forge install

      - name: Run forge tests
        run: forge test
        env:
          FOUNDRY_PROFILE: production
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}

  # Run fuzz tests.
  fuzz:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Run integration tests.
  integration:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Run invariant tests.
  invariants:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Run formal verification.
  verify:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Generate code coverage report.
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Generate code coverage report
        run: |
          forge coverage --report lcov
          sudo apt-get install lcov
          lcov --remove ./lcov.info -o ./lcov.info.pruned 'tests/*'

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: lcov.info.pruned
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./

  # Generate gas usage report.
  gas:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Generate documentation from NatSpec.
  docs:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Run static analysis.
  slither:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO

  # Package artifacts for publishing.
  package:
    runs-on: ubuntu-latest
    needs:
    steps:
      - run: echo TODO
