name: Forge Tests (PR)

on: [pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Specify version when it becomes possible to do so.
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          forge install

      - name: Run tests
        run: forge test

  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Foundry
      uses: onbjerg/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install submodules
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init --recursive
    - name: Generate coverage report
      run: |
        forge coverage --report lcov

    - name: Install lcov
      run: sudo apt-get install lcov

    - name: Remove Tets from coverage
      run:  lcov --remove ./lcov.info -o ./lcov.info.pruned 'tests/*'

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: lcov.info.pruned
        minimum-coverage: 50
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./
