name: Forge Tests (PR)

on: [pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Specify version when it becomes possible to do so.
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      # Add additional SSH keys if needed.
      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS: ${{secrets.SSH_KEY_GLOBALS}}
        shell: bash
        run: |
          chmod +x ./setup.sh
          ./setup.sh

      - name: Run tests
        run: forge test
