name: Forge Tests (PR)

on: [pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Specify version when it becomes possible to do so.
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      # Add SSH keys where needed.
      - name: Install submodules
        run: forge install

      - name: Run forge tests
        run: forge test
