name: Forge Tests (PR)

on: [pull_request]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}

        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make e2e profile=production
